server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinemaweb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: phuong4404
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd
    time-format: HH:mm:ss
  mail:
    host: smtp.gmail.com
    port: 587
    username: buihaiphupng6@gmail.com
    password: mdfabuwjbybeuaal
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  signerKey: "fAhsFQLtyhPPawzKmGDEU/IDeBpV7nGnIaQIWYZCzh8qGSb+ETsbFOoMfwfNsUgA"

