-- MySQL Script generated by MySQL Workbench
-- Mon May 19 12:16:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cinemaweb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cinemaweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cinemaweb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cinemaweb` ;

-- -----------------------------------------------------
-- Table `cinemaweb`.`cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`cinema` (
  `cinema_id` INT NOT NULL AUTO_INCREMENT,
  `cinema_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `cinema_address` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`cinema_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`room` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `cinema_id` INT NOT NULL,
  `room_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_cinema_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_cinema`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinemaweb`.`cinema` (`cinema_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`seat` (
  `seat_id` INT NOT NULL AUTO_INCREMENT,
  `seat_type` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `room_id` INT NOT NULL,
  `seat_row` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `seat_number` INT NOT NULL,
  `seat_price` DOUBLE NOT NULL,
  `seat_state` BIT(1) NOT NULL,
  PRIMARY KEY (`seat_id`),
  INDEX `fk_seat_room_idx` (`room_id` ASC) VISIBLE,
  CONSTRAINT `fk_seat_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `cinemaweb`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`movie` (
  `movie_id` INT NOT NULL AUTO_INCREMENT,
  `movie_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_poster` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `movie_genre` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `movie_length` INT NOT NULL,
  `movie_description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `movie_review` INT NULL DEFAULT NULL,
  PRIMARY KEY (`movie_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `schedule_date` DATE NOT NULL,
  `schedule_start` TIME NOT NULL,
  `schedule_end` TIME NOT NULL,
  `cinema_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `fk_schedule_room_idx` (`room_id` ASC) VISIBLE,
  INDEX `fk_schedule_film_idx` (`movie_id` ASC) VISIBLE,
  INDEX `FKuk1m56gbrdyomvctf1teeefe` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `fk_schedule_film`
    FOREIGN KEY (`movie_id`)
    REFERENCES `cinemaweb`.`movie` (`movie_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_schedule_room`
    FOREIGN KEY (`room_id`)
    REFERENCES `cinemaweb`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKuk1m56gbrdyomvctf1teeefe`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinemaweb`.`cinema` (`cinema_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`user` (
  `user_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `username` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `password` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `first_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `last_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `date_of_birth` DATE NOT NULL,
  `gender` INT NULL DEFAULT NULL,
  `avatar` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `point` DOUBLE NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `schedule_id` INT NOT NULL,
  `price` DOUBLE NOT NULL,
  `booking_day` DATETIME(6) NULL DEFAULT NULL,
  `seat_id` INT NULL DEFAULT NULL,
  `user_id` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `UKjx9a9qmksuasu3taidjqyp0co` (`user_id` ASC) VISIBLE,
  INDEX `fk_booking_schedule_idx` (`schedule_id` ASC) VISIBLE,
  INDEX `FK7ryitbom1ln9okwlj2t9tt9ym` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `FK7ryitbom1ln9okwlj2t9tt9ym`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinemaweb`.`seat` (`seat_id`),
  CONSTRAINT `fk_booking_schedule`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `cinemaweb`.`schedule` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FKkgseyy7t56x7lkjgu3wah5s3t`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemaweb`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`booking_seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`booking_seat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NULL DEFAULT NULL,
  `seat_id` INT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `booking_id` (`booking_id` ASC) VISIBLE,
  INDEX `seat_id` (`seat_id` ASC) VISIBLE,
  CONSTRAINT `booking_seat_ibfk_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `cinemaweb`.`booking` (`booking_id`),
  CONSTRAINT `booking_seat_ibfk_2`
    FOREIGN KEY (`seat_id`)
    REFERENCES `cinemaweb`.`seat` (`seat_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`foodanddrink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`foodanddrink` (
  `fd_id` INT NOT NULL AUTO_INCREMENT,
  `fd_name` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `cinema_id` INT NOT NULL,
  `fd_price` DOUBLE NOT NULL,
  `image_food_and_drink` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`fd_id`),
  INDEX `fk_foodanddrink_room_idx` (`cinema_id` ASC) VISIBLE,
  CONSTRAINT `FK2bfct4r9wwpgl4ee44p4kydrn`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinemaweb`.`cinema` (`cinema_id`),
  CONSTRAINT `fk_foodanddrink_room`
    FOREIGN KEY (`cinema_id`)
    REFERENCES `cinemaweb`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`bookingfoodanddrink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`bookingfoodanddrink` (
  `booking_fd_id` INT NOT NULL AUTO_INCREMENT,
  `booking_id` INT NULL DEFAULT NULL,
  `fd_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`booking_fd_id`),
  INDEX `booking_id` (`booking_id` ASC) VISIBLE,
  INDEX `fd_id` (`fd_id` ASC) VISIBLE,
  CONSTRAINT `bookingfoodanddrink_ibfk_1`
    FOREIGN KEY (`booking_id`)
    REFERENCES `cinemaweb`.`booking` (`booking_id`),
  CONSTRAINT `bookingfoodanddrink_ibfk_2`
    FOREIGN KEY (`fd_id`)
    REFERENCES `cinemaweb`.`foodanddrink` (`fd_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`invalidated_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`invalidated_token` (
  `id` VARCHAR(255) NOT NULL,
  `expiry_time` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`password_otp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`password_otp` (
  `otp` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expiry_time` DATETIME(6) NOT NULL,
  `valid` TINYINT(1) NOT NULL,
  `user_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`otp`),
  INDEX `fk_password_otp_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_password_otp_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemaweb`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`permission` (
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`role` (
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `description` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`role_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`role_permissions` (
  `role_name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `permission_name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`role_name`, `permission_name`),
  INDEX `fk_role_has_permission_permission1_idx` (`permission_name` ASC) VISIBLE,
  INDEX `fk_role_has_permission_role1_idx` (`role_name` ASC) VISIBLE,
  CONSTRAINT `fk_role_has_permission_permission1`
    FOREIGN KEY (`permission_name`)
    REFERENCES `cinemaweb`.`permission` (`name`),
  CONSTRAINT `fk_role_has_permission_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `cinemaweb`.`role` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `cinemaweb`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cinemaweb`.`user_roles` (
  `user_id` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `role_name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  PRIMARY KEY (`user_id`, `role_name`),
  INDEX `fk_user_has_role_role1_idx` (`role_name` ASC) VISIBLE,
  INDEX `fk_user_has_role_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_name`)
    REFERENCES `cinemaweb`.`role` (`name`),
  CONSTRAINT `fk_user_has_role_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `cinemaweb`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
